### PR TITLE
fixed mac crashes by removing timout function

### LINKED ISSUE #40: Onboarding lucien
- [x] oude expander weghalen
- [ ] niet werkende tests weghalen
- [x] expander integreren

### PR DESCRIPTION
**Pull request by saladuit**
I just removed a timeout check which resolved a lot of crashes closes #40

### CODE REVIEW

File: unit_test/src/env_cases.c [hunk 1]
```diff
@@ -10,6 +10,7 @@ void assert_envp_load(char **input,char *key, char *expected)
 {
   t_dictionary env[HASH_TABLE_SIZE];
 
+  bzero(env, sizeof(env));
```
Comment (lucienvb) [inline unit_test/src/env_cases.c:13]: FIXME: ft_bzero

**Review by lucienvb — CHANGES_REQUESTED** [review]
Fix the FIXME please.

**Review by lucienvb — APPROVED** [review]
